### ISSUE TITLE
Counts matrix for Transcriptomic data

### ISSUE THREAD

**Issue by EronHou** [AllenInstitute/coupledAE-patchseq#4]
1. The [link](http://data.nemoarchive.org/other/grant/AIBS_patchseq/transcriptome/scell/SMARTseq/processed/analysis/20200611/) for the raw transcriptomic data mentioned in the [paper](https://www.nature.com/articles/s43588-021-00030-1) returns an error. 
2. I found the data through the [brain-map portal](https://portal.brain-map.org/explore/classes/multimodal-characterization) instead; here one sample `specimen id = 866393577` is missing.

**Comment by EronHou** [comment]
I can find gene symbols now. But the single cell indexed with 866393577 is not included in the link https://portal.brain-map.org/explore/classes/multimodal-characterization.

**Comment by EronHou** [comment]
@rhngla

**Comment by rhngla** [comment]
Hi @EronHou:
1. The link for the archive mentioned in the paper was unfortunately revised subsequently; [this is the updated link](http://data.nemoarchive.org/other/AIBS/AIBS_patchseq/transcriptome/scell/SMARTseq/processed/analysis/20200611/)
2. We also noticed the sample missing from the archive previously (see [this gist](https://gist.github.com/rhngla/a47321469a4d18cc3ecefc57edbff028)). It turns out this sample had QC related issues which were discovered later, and therefore it was excluded from the archived version. It would be alright to discard the transcriptomic profile for this sample from downstream analysis.
